<a href="https://colab.research.google.com/github/robertosgpontes/tec_prog_1/blob/main/ExerciciosNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lista de Exercícios de Numpy

Deverá ser entrege até **11/02/2023** por meio do github que foi informado por vocês no [formulário](https://forms.office.com/r/YV12vEXGYF) respondido na aula de 01/02.

A entrega pela github é parte da avaliação.

## Questão 1

Crie um array 100 com valores aleatórios e ache os valores máximo e mínimo

In [1]:
import numpy as np

randn_values = np.random.randn(100)
print('Dados: ', randn_values)

print(' ')
print('Valor máximo: ', randn_values.max())
print('Valor mínimo: ', randn_values.min())

Dados:  [ 0.24452839 -0.26934691  0.38042931  0.84615683  1.54083012 -0.25200877
  0.7946883  -0.04206927 -0.79025837  0.56732558  0.23075668 -0.86330918
 -0.3968693  -1.16880675  0.70332961  1.36906274  0.06224124 -1.95087895
  0.13493382  0.88715508  1.33944967  0.90985248  0.03777018 -0.32087915
  0.35518354  0.2652457   0.3931793  -0.09053337 -0.38143916  2.3200905
 -0.6365928  -0.0898881  -0.87811153  0.55693289 -1.40410454 -0.10573485
  0.42781855 -0.48826047 -1.6160142   0.21075947  0.73111341  1.0337812
  0.15036621 -0.01672773 -0.09835827  0.49808111 -0.03363591 -0.28037189
 -2.07027116 -2.11539429 -1.38045471  1.71371052 -1.1682931   1.5165104
 -0.34523264 -1.70994464 -0.81018257 -0.13224654  0.18518551  1.51858239
  2.81118019  0.63006436 -0.34605032  0.63427012  0.97677713 -1.53516663
 -0.11575782 -0.1201285  -1.76373415 -0.09197035  1.26613514 -0.49928859
  1.77690093  0.90817237 -0.03887419  0.8238057   0.59453192 -1.04501383
 -0.23440066  1.37747811  0.20079736 -0.502770

## Questão 2
Em Geometria Analítica, um **vetor** é uma quantidade que pode ser definida por um énuplo (uma sequência ordenada de *n* elementos) em que cada elemento representa a intensidade do vetor na direção especificada pela i-ésima componente desta sequência. 

Quando pensamos em duas dimensões, por exemplo, o vetor $R = (b,a)$ define, geometricamente, a entidade representada na figura abaixo, com componentes nos eixos x e y usuais.

<img src = "https://static.todamateria.com.br/upload/im/ag/image-721.jpg?auto_optimize=low" />

O **módulo** deste vetor, também chamado de intensidade, está geometricamente relacionado ao seu comprimento, e pode ser calculado diretamente pelas suas componentes, por meio de uma operação conhecida como **produto escalar** do vetor com ele mesmo. O módulo quadrático é expresso, desta forma, por:

$|A|^2 = \vec{A} \cdot \vec{A}$

Por outro lado, o produto escalar entre dois vetores $A = (a_{x}, a_{y})$ e $B = (b_{x}, b_{y})$ é dado por:

$\vec{A} \cdot \vec{B} = a_{x} \times b_{x} + a_{y} \times b_{y}$ (e esta definição vale para qualquer que seja a dimensão do vetor).

O módulo quadrático de um vetor é, portanto:

$|A|² = a_{x}^2 + b_{x}^2$.

Dado o exposto acima, escreva uma função que retorne o módulo de um vetor n-dimensional qualquer.

In [6]:
import numpy as np

In [2]:
def get_module_value(vt):
    module_value = (np.sum(vt**2))**(1/2)
    return module_value

vt = np.array ([1,2,3,4,5])

module = get_module_value(vt)

print('Modulo do vetor: ', module)

Modulo do vetor:  7.416198487095663


In [7]:
%%timeit 

def modulo(vetor):
  return (np.sum(vetor**2))**(1/2)

#dim = int(input('Qual a dimensão do vetor?'))
#vetor = np.random.randint(0,100,dim)

modulo(np.array([22, 70]))

25.3 µs ± 8.44 µs per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [8]:
%%timeit 
def modulo(vetor):
  modulo=((vetor*vetor).sum())**(1/2)
  return modulo

modulo(np.array([22, 70]))

13.9 µs ± 3.26 µs per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


## Questão 3

Em uma **análise de regressão**, usualmente estamos interessados em descrever relações entre variáveis de um dado conjunto de dados por meio de uma **função** que descreva, o tanto quanto possível, estas relações.

Por exemplo, no gráfico abaixo, os pontos vermelhos relacionam as medidas das duas variáveis sendo avaliadas (nos eixos x e y); e a linha azul aproxima a relação entre elas por uma função linear.

![Normdist_regression.png](https://miro.medium.com/v2/resize:fit:786/format:webp/1*LEmBCYAttxS6uI6rEyPLMQ.png)

É possível ver que nem todos os pontos obedecem exatamente à relação ditada pela reta (isto é, há pontos que não estão exatamente "sobre a reta"; mas, sim, ligeraimente acima, ou abaixo, dela). Isto, contudo, é esperado em um modelo de regressão, por inúmeras fontes de incerteza associadas às medições.

Uma das métricas que utilizamos para avaliar a qualidade de uma regressão é o **erro quadrático médio (EQM)**, que mensura a diferença total entre cada predição da regressão ($y_{prediction}$; que no nosso caso seriam os valores de y para a reta azul) com o valor real de cada i-ésima medida ($y_{i}$; que no nosso caso seriam as coordenadas y para cada ponto vermelho do gráfico). O EQM pode ser definido como:

$EQM = \frac{1}{n}\sum_{i=1}^{n}(y_{prediction} - y_{i})^2$.

Isto posto, escreva uma função que calcule o EQM recebendo, como entrada, os vetores $y_{prediction}$ e $y_{i}$. Por exemplo, digamos que sua função se chame *calculate_eqm*, ela deve operar da seguinte forma:

```python

# dados dois arrays quaisquer de mesmo tamanho, a função deve retornar o EQM
y_prediction = np.array([1,2,3])
y_i = np.array([0,0,3])
calculate_eqm(y_prediction,y_i)

>>> 1.6666666666666665

```

In [3]:
# Solução
def get_eqm_value(y_pred, y_i):
    EQM = (np.subtract(y_pred,y_i)**2).mean()
    return EQM

y_prediction = np.array([1,2,3])
y_i = np.array([0,0,3])

EQM = get_eqm_value(y_prediction, y_i)

print('Valor do EQM: ', EQM)

Valor do EQM:  1.6666666666666667


## Questão 4

Crie um array 2D (bidimensional) com 1 na borda e 0 dentro

In [30]:
def create_external_matriz_zeros(Nrows, Ncol):
    
    zeros = np.zeros(
        (Nrows, Ncol)
    )
    
    matriz =  np.pad(
        zeros,
        pad_width=1, 
        mode='constant', 
        constant_values=1
    )

    print(matriz)

create_external_matriz_zeros(10, 5)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


## Questão 5

Como adicionar uma borda de 0's ao redor de um array 2D (bidimensional) existente

In [ ]:
def create_external_matriz_ones(Nrows, Ncol):
    
    zeros = np.ones(
        (Nrows, Ncol)
    )
    
    matriz =  np.pad(
        zeros,
        pad_width=1, 
        mode='constant', 
        constant_values=0
    )

    print(matriz)

create_external_matriz_ones(10, 5)


## Questão 6

 A eletroencefalografia (EEG) é uma técnica que mensura potenciais elétricos cerebrais em diversas regiões do escalpo do paciente. Suponha que você recebeu um conjunto de dados na forma de uma matriz de 64 x 512 elementos, em que cada linha contém o sinal gravado em um dos **eletrodos** espalhados pelo escalpo em um exame de EEG, e cada coluna contém um valor de potencial elétrico, em microvolts. 

Como o sinal de EEG é muito suscetível a ruídos externos (interferências na qualidade do sinal), uma operação comum para atenuar a interferência no sinal consiste em tirar a média do potencial elétrico de todos os eletrodos, e subtrair este valor de cada um deles. Isto atenua fontes de ruído ao sinal comuns a todos os eletrodos. Em termos matemáticos, o sinal processado por esta operação, $X_{e,i}$ para cada eletrodo (e) e amostra (i), é dado por:

$X_{e,i} = \hat{X_{e,i}} - \frac{1}{N}\sum_{e=1}^{N}\hat{X_{e,i}}$,

em que $\hat{X_{e,i}}$ representa o sinal original (ou seja, é a matriz de entrada de 64 x 512 elementos), e $N$ indica o total de eletrodos.

Com o exposto acima, escreva uma função que retorne uma matriz com os sinais de EEG processados conforme a operação mencionada. Sua função deve operar conforme o exemplo abaixo.

In [34]:
def get_filter_egg_signal(signal):
    filter_signal = signal - signal.mean()
    
    return filter_signal

signal = np.random.rand(64,512)

filter_signal = get_filter_egg_signal(signal)

filter_signal

array([[ 0.40824287,  0.03852702,  0.49311571, ...,  0.31736461,
        -0.28381931,  0.2140262 ],
       [-0.39144058, -0.10873636, -0.44385669, ..., -0.06991583,
        -0.18465586,  0.39777932],
       [-0.23419578,  0.26549013, -0.37512737, ...,  0.31579664,
         0.13384141, -0.36107738],
       ...,
       [ 0.1558203 ,  0.24693203,  0.3927658 , ..., -0.47948338,
        -0.42004291, -0.42785322],
       [-0.47856218, -0.35258052,  0.13060524, ..., -0.06810407,
        -0.05237275,  0.08641852],
       [ 0.20190308, -0.21353791, -0.38127347, ..., -0.26922938,
        -0.46206863, -0.32874457]])

## Questão 7

Em estatística, um **outlier** é um valor que destoa consideravelmente da distribuição à qual está associado. Um dos critérios para idenficar outliers consiste em encontrar a **distância interquantil** (IQR), ou seja, a diferença entre o terceiro (Q3) e o primeiro quartis (Q1) da distribuição, e tomar como outliers todos os pontos abaixo do Limite Inferior (LI = Q1 - 1.5*IQR  ), ou acima do Limite Superior (LS = Q3 + 1.5*IQR).

![image.png](https://s3-sa-east-1.amazonaws.com/lcpi/0d8a7b04-b982-4e6b-9fc7-fbb062247d8d.png)


<img src = "https://blog.curso-r.com/images/posts/banner/outlier.webp" />

Escreva uma função que, dada uma matriz de dados de entrada de dimensões $N_{observações} \times N_{features}$ retorne três requisitos: 
- uma matriz booleana indicando a existência de outliers nos dados de entrada;
- a quantidade de outliers
- quem são os outliers (os valores).

**Algumas definições:**
- um *quantil* divide a distribuição, após ordenados os pontos, segundo algum ponto de corte;
- o **primeiro quartil** é o ponto para o qual 25 % dos valores da distribuição estão abaixo dele;
- o **terceiro quartil** é o ponto para o qual 75 % dos valores da distribuição estão abaixo dele.

Pode ser útil consultar a função **numpy.quantile**.

Exemplo de operação da função:

```python
# Geremos um conjunto de dados qualquer
X = np.random.randn(300,15)
X

>>> array([[-2.02108952,  0.57945921, -2.23074965, ..., -0.60349514,
         0.92180452, -0.15625722],
       [ 0.24904397,  0.03493447,  0.3515052 , ..., -0.46950081,
         0.20361331,  0.02715956],
       [ 0.55902525, -0.48435434,  0.90413414, ..., -0.54425743,
        -0.80769134, -0.07912549],
       ...,
       [-1.04069388, -0.24245725, -2.00308877, ...,  0.4084777 ,
        -1.81516131,  0.39063118],
       [-1.39275097,  0.3989636 ,  0.2926223 , ...,  1.2620666 ,
         0.72262949,  1.50737559],
       [ 0.15922011, -0.79810788, -1.60939896, ..., -0.08214499,
        -0.13167475,  0.15990558]])


# identificamos os requisitos com nossa com nossa função "locate_outliers"
is_outlier, outliers_count, outliers = locate_outliers(X)

is_outlier
>>> array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

outliers_count
>>> 44

outliers
>>> array([-2.67240384,  3.00270904,  3.62317101,  3.18867865,  2.55581522,
       -2.82091429,  2.8757892 ,  2.70666036,  3.19514999, -3.40550318,
       -3.39825827,  2.6727295 ,  2.54498296, -2.69447104,  3.19521603,
        2.66372172, -2.77444948,  2.77421152,  2.69992869, -2.84831109,
       -2.83695779, -2.45908227,  3.07802106,  2.89314015, -2.68574682,
       -2.85019494,  2.43399574,  2.44291266, -2.92595937, -2.95911074,
       -3.03966003,  2.77543068, -2.67368414, -2.79965402, -3.0501958 ,
       -2.5437387 ,  3.08550649, -3.17666255, -3.05795476, -3.09826467,
        3.1399469 ,  3.18141942,  2.90564257, -2.89505054])

 ``` 

## Questão 8

Crie um vetor com valores que vão de 1 até 21 de dois em dois, a partir da função arange

In [3]:
import numpy as np
vt = np.arange(1, 21, 2)
vt

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

## Questão 9

Crie um array de 10 com valores aleatórios

In [4]:
rand_values = np.random.randint(1,10,10)
rand_values

array([8, 5, 9, 9, 2, 2, 1, 7, 4, 5])

## Questão 10

Em estatística, a normalização de uma distribuição de dados pode ser feita subtraindo o valor médio da distribuição de cada valor do conjunto de dados, dividindo o resultado pelo desvio-padrão da distribuição. Escreva uma função que normalize os dados recebidos por um array numpy qualquer, conforme descrito anteriormente.

In [5]:
def get_normalize_vt(vt):
    std = vt.std()
    mean = vt.mean()

    vt_norm = (vt-mean)*(1/std)
    return vt_norm

vt = np.random.randint(1,5,100)

vt_norm = get_normalize_vt(vt)
print(vt_norm)

[-1.39002083 -0.41113292 -1.39002083  0.56775499 -0.41113292 -1.39002083
 -1.39002083 -1.39002083 -0.41113292 -0.41113292 -0.41113292  1.5466429
 -0.41113292  0.56775499 -0.41113292  1.5466429   1.5466429  -0.41113292
 -1.39002083 -1.39002083  0.56775499  1.5466429  -0.41113292 -0.41113292
 -0.41113292 -1.39002083 -1.39002083  0.56775499 -0.41113292  1.5466429
  1.5466429   0.56775499 -0.41113292  0.56775499 -0.41113292  0.56775499
 -1.39002083  0.56775499  1.5466429  -1.39002083 -0.41113292  0.56775499
 -0.41113292 -0.41113292 -1.39002083  0.56775499  1.5466429   1.5466429
  0.56775499  0.56775499 -0.41113292 -0.41113292 -1.39002083 -1.39002083
 -1.39002083  1.5466429   1.5466429   0.56775499  1.5466429  -0.41113292
  0.56775499  0.56775499 -0.41113292 -0.41113292  1.5466429  -0.41113292
  1.5466429   0.56775499 -1.39002083 -0.41113292  0.56775499  0.56775499
  1.5466429   0.56775499  0.56775499 -1.39002083  1.5466429   0.56775499
 -0.41113292 -0.41113292 -0.41113292 -0.41113292  0.56

## Questão 11

Escreva uma função em numpy que receba um array contendo notas de uma turma de 100 estudantes. Considere que a nota de aprovação da turma é 5.0. A função deve retornar, em um array numpy, nesta ordem:
- a média e o desvio-padrão das notas da turma;
- o número de notas maiores que 7.0;
- o número de reprovações da turma;
- a menor nota da turma;
- a maior nota da turma.

In [33]:
def inf_notas(notas):
    m=notas.mean()
    std_n=notas.std()
    max_n=notas.max()
    min_n=notas.min()
    maior_n= (notas[notas > 7]).size
    numero_rep = (notas[notas < 5]).size
    
    arry= np.array(
        [m,std_n,maior_n,numero_rep,max_n,min_n]
        )
    return arry

notas = np.random.randint(0, 11, 100)
print(inf_notas(notas))


[ 4.25       2.8473672 15.        54.        10.         0.       ]
